bundle_cache: &bundle_cache
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_OS
      - ruby -v
      - cat Gemfile
      - cat *.gemspec
  install_script: bundle update

markdownlint_task:
  container:
    image: ruby:latest
  <<: *bundle_cache
  rubocop_script: bundle exec mdl .

rubocop_task:
  container:
    image: ruby:latest
  <<: *bundle_cache
  rubocop_script: bundle exec rubocop

test_task:
  depends_on:
    - rubocop
    - markdownlint
  container:
    matrix:
      image: ruby:2.5
      image: ruby:2.6
      image: ruby:2.7
  <<: *bundle_cache
  environment:
    CODECOV_TOKEN: ENCRYPTED[de650f17db291399a09839a898ab3be8d0bb09a14b369f16f31a1831d6db8d826d4601ea7ad87eab99d005ad832846cc]
  test_script: bundle exec rake
