require:
  - rubocop-performance
  - rubocop-rspec

Layout/IndentationStyle:
  EnforcedStyle: tabs
  IndentationWidth: 2
Layout/IndentationWidth:
  Width: 1
Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*.rb

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

RSpec/NestedGroups:
  Max: 6
RSpec/RepeatedExampleGroupBody:
  Exclude:
    ## Variables are generating from context description
    - spec/example_file_spec.rb
